In [3]:
#bd - birthday age - 0 - значит мусор
#registered_via - код способа регистрации пользователя

import pandas as pd

df = pd.read_csv('members.csv')
df.info()
df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_15024\372030570.py:5: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('members.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6769473 entries, 0 to 6769472
Data columns (total 6 columns):
 #   Column                  Dtype
---  ------                  -----
 0   msno                    object
 1   city                    int64
 2   bd                      int64
 3   gender                  object
 4   registered_via          int64
 5   registration_init_time  int64
dtypes: int64(4), object(2)
memory usage: 309.9+ MB

,msno,city,bd,gender,registered_via,registration_init_time
0,kfe7o/IQJT+yPQnDM8Ru67XrTWCutEg20xinHKy6UxU=,1,0,NaN,7,20120320
1,hkNDL7tng+4wVvrm5FGqTgaXMElTauo16CqxE63pavM=,1,0,NaN,7,20120320
2,0eAH4euZqyyUreUiIASJ1cqYc0OBpvBFtxAz81bXl+s=,1,0,NaN,7,20120320
3,dKTlgMn0d/UAglVcVUIS7bKv2d82Veahl4rbxhCtv/I=,1,0,NaN,7,20120320
4,rAdkP5n4ra8lkTKZRqxLOyi+XJ9Enw++Nqtmx1XxilY=,1,0,NaN,7,20120320

In [4]:
#посчитаем все значения, включая NaN
df['gender'].value_counts(dropna=False)

gender
NaN       4429505
male      1195355
female    1144613
Name: count, dtype: int64

In [15]:
df['bd'].describe()

count    6.769473e+06
mean     9.795794e+00
std      1.792590e+01
min     -7.168000e+03
25%      0.000000e+00
50%      0.000000e+00
75%      2.100000e+01
max      2.016000e+03
Name: bd, dtype: float64

In [5]:
df['bd'].value_counts().head(15)

bd
0     4540215
22     112200
21     110574
20     110452
27     102769
23     101500
24      97252
26      92433
25      91514
19      91374
18      90659
28      82722
17      82111
29      82026
30      70443
Name: count, dtype: int64

In [8]:
#найдем пропуски
df.isna().sum()

msno                            0
city                            0
bd                              0
gender                    4429505
registered_via                  0
registration_init_time          0
dtype: int64

In [9]:
#пол заполнен примерно на 35%, то есть чуть больше трети от всех пользователей. 
df['gender'].isna().mean() * 100

np.float64(65.43352783887313)

In [10]:
df['gender'].value_counts(dropna=False)

gender
NaN       4429505
male      1195355
female    1144613
Name: count, dtype: int64

In [11]:
#заполним NaN
df['gender'] = df['gender'].fillna('unknown')

In [20]:
df[df['bd'] < 0]['bd'].value_counts().head()

bd
-48    19
-51    18
-49    16
-50    13
-43    12
Name: count, dtype: int64

In [22]:
df[df['bd'] > 100]['bd'].value_counts().head()

bd
112    1309
106     743
103     449
117     439
102     424
Name: count, dtype: int64

In [29]:
#число 0
print((df['bd'] == 0).mean() * 100)
print((df['bd'] < 0).mean() * 100)
print((df['bd'] > 100).mean() * 100)

67.06895795285689
0.004047582433669504
0.07943011221109826

In [31]:
#первый вывод
count_zero = (df['bd'] == 0).sum()
pct_zero = (df['bd'] == 0).mean() * 100
print(f'Возраст не указан у {count_zero:,} пользователей ({pct_zero:.1f}%)')

Возраст не указан у 4,540,215 пользователей (67.1%)

In [33]:
#теперь оставим только нормальный возраст
df.loc[(df['bd'] <= 0) | (df['bd'] > 100), 'bd'] = pd.NA

In [47]:
#следующий стоблик: город city
df['city'].value_counts().head()

city
1     4804326
5      385069
13     320978
4      246848
22     210407
Name: count, dtype: int64

In [41]:
df['city'].nunique()

21

In [44]:
df['city'].describe()

count    6.769473e+06
mean     3.847358e+00
std      5.478359e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      4.000000e+00
max      2.200000e+01
Name: city, dtype: float64

In [46]:
#посчитаем долю с city = 1
(df['city'] == 1).mean() * 100

np.float64(70.97045811394771)

In [49]:
#registered_via - код способа регистрации пользователя

df['registered_via'].value_counts().head(10)

registered_via
4     2793213
3     1643208
9     1482863
7      805895
11      25047
13       5455
8        3982
5        3115
17       1494
2        1452
Name: count, dtype: int64

In [51]:
df['registered_via'].nunique()

18

In [53]:
df['registered_via'].value_counts(normalize=True).head(10) * 100

registered_via
4     41.261897
3     24.273795
9     21.905147
7     11.904841
11     0.369999
13     0.080582
8      0.058823
5      0.046015
17     0.022070
2      0.021449
Name: proportion, dtype: float64

In [55]:
#registration_init_time

df['registration_init_time'] = pd.to_datetime(
    df['registration_init_time'].astype(str),
    format='%Y%m%d'
)

In [59]:
print(df['registration_init_time'].min())
print(df['registration_init_time'].max())

2004-03-26 00:00:00
2017-04-29 00:00:00

In [61]:
#сколько польз регались в год (2017 - неполный)
df['registration_init_time'].dt.year.value_counts().sort_index()

registration_init_time
2004      26234
2005      41349
2006      53953
2007      89830
2008      67690
2009      63633
2010     115075
2011     179051
2012     283190
2013     524722
2014     975776
2015    1620525
2016    2246761
2017     481684
Name: count, dtype: int64

In [62]:
df[df['registration_init_time'].dt.year == 2017]['registration_init_time'].dt.month.value_counts().sort_index()

registration_init_time
1    163721
2    163797
3     99072
4     55094
Name: count, dtype: int64

In [63]:
df[df['registration_init_time'].dt.year == 2016]['registration_init_time'].dt.month.value_counts().sort_index()

registration_init_time
1     253156
2     208170
3     195618
4     178329
5     184404
6     189359
7     189273
8     176584
9     163065
10    170302
11    165057
12    173444
Name: count, dtype: int64

In [69]:
print('Строк:', len(df))
print('Уникальных msno:', df['msno'].nunique())
print('Дубликатов msno:', df['msno'].duplicated().sum())

Строк: 6769473
Уникальных msno: 6769473
Дубликатов msno: 0

In [70]:
#перейдем к файлу transactions.csv
#код способа оплаты, plan_list_price — стандартная цена тарифа, actual_amount_paid - сколько польз заплатил, если меньше, то скидка
#is_auto_renew - автопродление
#membership_expire_date - дата до которой действует подписка

df_transactions = pd.read_csv('transactions.csv')
df_transactions.head()

,msno,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
0,++6eU4LsQ3UQ20ILS7d99XK8WbiVgbyYL4FUgzZR134=,32,90,298,298,0,20170131,20170504,0
1,+kdzMTBwnWkFvWCLiK94UXAzRubMomjCNXTpqVlM/WM=,20,100,480,480,0,20170107,20170417,0
2,+weVl2uf/jJEy1ziJb8OGWAyEOOEtzr4WGlSacjolgo=,38,365,1299,1299,0,20170115,20180115,0
3,/R6+tah0zuDQIQPr80CiuQMfqIxrQS0aRX5u7STjpGM=,32,180,699,699,0,20161218,20170616,0
4,/m9G2inXqltccUgil2basIPC3WKx2vyS6nueJoxPDxw=,38,365,1299,1299,0,20161103,20171215,0

In [71]:
df_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1431009 entries, 0 to 1431008
Data columns (total 9 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   msno                    1431009 non-null  object
 1   payment_method_id       1431009 non-null  int64
 2   payment_plan_days       1431009 non-null  int64
 3   plan_list_price         1431009 non-null  int64
 4   actual_amount_paid      1431009 non-null  int64
 5   is_auto_renew           1431009 non-null  int64
 6   transaction_date        1431009 non-null  int64
 7   membership_expire_date  1431009 non-null  int64
 8   is_cancel               1431009 non-null  int64
dtypes: int64(8), object(1)
memory usage: 98.3+ MB

In [73]:
df_transactions.shape

(1431009, 9)

In [74]:
df_transactions['payment_plan_days'].value_counts().head(10)

payment_plan_days
30     1217998
410      82097
195      28568
180      23900
90       19130
7        12168
395       9753
360       4658
100       4098
365       3838
Name: count, dtype: int64

In [75]:
df_transactions['payment_plan_days'].describe()

count    1.431009e+06
mean     6.601770e+01
std      1.024864e+02
min      0.000000e+00
25%      3.000000e+01
50%      3.000000e+01
75%      3.000000e+01
max      4.500000e+02
Name: payment_plan_days, dtype: float64

In [76]:
df_transactions[df_transactions['payment_plan_days'] <= 0]['payment_plan_days'].value_counts()

payment_plan_days
0    2218
Name: count, dtype: int64

In [77]:
df_transactions['payment_plan_days'].max()

np.int64(450)

In [79]:
df_transactions[df_transactions['payment_plan_days'] == 0].head(15)

,msno,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
24719,0bAK8hFztHoYGFNDktYu66rw4KWeOnvcnlLxsuXSXSw=,41,0,0,149,1,20150426,20170624,1
24726,8NOQhq2g9B4hhDQbhUuwXBOmp6mNfLwxmhGdDDG9fHY=,41,0,0,149,1,20150507,20180407,0
24728,Br7RsrWv9YQA1q1ped0of+umU6/s3FgDCfJ/C4z/90Y=,41,0,0,149,1,20150501,20181205,0
24729,C1h8A4MS1ounYf4DkMN316gXlSTMK8xIHLI16sPa/is=,41,0,0,119,1,20150424,20170724,0
24730,HGKfudttieegLoo89jy/76cUuqCzVA76I/yRJ0GZvZA=,41,0,0,149,1,20150505,20170703,1
24731,Iw/oJ98lTiX5PLT7FTUBF+ArbxWy+hKXDce/E3sEIOg=,41,0,0,119,1,20150512,20170720,0
24735,ON6yKHrrrY3jMG/XQNavm/PHIQkUHp7i0z/EpVT7HAI=,41,0,0,149,1,20150502,20170730,0
24740,YhgbxZ/7k5D2fTDq70Jxmcc2ptOlFVRc3dI5DHAw9l4=,41,0,0,149,1,20150508,20170407,0
24741,aVW/fpY2xNAAsuk1DQIPIA+L3n0ZsF4S8qsonfbbfgc=,41,0,0,149,1,20150513,20180413,0
24745,gL68ozJdVJDdq9Ah8oQHnmD1EuOWy0vNiNqV1rWfulQ=,41,0,0,149,1,20150425,20170519,0
24748,h24IACT3QIvH8U1zSNpX3eT7db8nLxjZluHcznUeLXE=,41,0,0,149,1,20150425,20170624,0
24749,jQFw9WUFRVeMfDnnDhwsIF5IfdocW0vcGlULgOSeA8Q=,41,0,0,149,1,20150509,20170408,0
24751,kXDzsZ189uCp2ij0XWrW/g1xWrgdit+m/HPsZmO+ZFg=,41,0,0,149,1,20150501,20180430,0
24753,mFE7bNK4EqZJ7I5KEa0jsii9LaHIW0elj4xVp64K9R8=,41,0,0,149,1,20150427,20190822,0
24754,o5aFK3grQrjlHACDVvS0cPa1KvLq9x9KeTM/L2SgLz0=,41,0,0,119,1,20150425,20190613,0

In [82]:
df_transactions[df_transactions['payment_plan_days'] == 0]['payment_method_id'].value_counts()

payment_method_id
41    2169
38      28
32      16
26       3
5        1
24       1
Name: count, dtype: int64

In [83]:
df_transactions[
    df_transactions['payment_plan_days'] == 0
]['is_cancel'].value_counts(normalize=True) * 100

is_cancel
0    98.016231
1     1.983769
Name: proportion, dtype: float64

In [84]:
df_transactions['is_auto_renew'].value_counts().head()

is_auto_renew
1    1123775
0     307234
Name: count, dtype: int64

In [85]:
df_transactions.groupby('is_auto_renew')['is_cancel'].mean() * 100

is_auto_renew
0    0.000000
1    3.126338
Name: is_cancel, dtype: float64

In [86]:
#посмотрим цены
df_transactions[['plan_list_price', 'actual_amount_paid']].describe()

       plan_list_price  actual_amount_paid
count     1.431009e+06        1.431009e+06
mean      2.817870e+02        2.813172e+02
std       4.351861e+02        4.354200e+02
min       0.000000e+00        0.000000e+00
25%       9.900000e+01        9.900000e+01
50%       1.490000e+02        1.490000e+02
75%       1.490000e+02        1.490000e+02
max       2.000000e+03        2.000000e+03

In [87]:
#в 67% случаев пользователь платит меньше прайса
(df_transactions['actual_amount_paid'] < df_transactions['plan_list_price']).mean() * 100

np.float64(0.6735806693039667)

In [88]:
(df_transactions['actual_amount_paid'] <= 0).sum()

np.int64(21448)

In [94]:
print(df_transactions['transaction_date'].min(),
      df_transactions['transaction_date'].max())

print(df_transactions['membership_expire_date'].min(),
      df_transactions['membership_expire_date'].max())

2015-01-01 00:00:00 2017-03-31 00:00:00
2016-04-19 00:00:00 2036-10-15 00:00:00

In [95]:
# 3. Есть ли "окончание подписки" раньше транзакции
(
    df_transactions['membership_expire_date']
    < df_transactions['transaction_date']
).sum()

np.int64(5106)

In [96]:
df_transactions['msno'].nunique()

1197050

In [98]:
df_transactions.groupby('msno').size().describe()

count    1.197050e+06
mean     1.195446e+00
std      1.206252e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      2.080000e+02
dtype: float64

In [99]:
df_transactions.groupby('msno').size().sort_values(ascending=False).head(10)

msno
72gJqt1O31E/WoxAEYFn9LHNI6mAZFGera5Q6gvsFkA=    208
5ty4nZkq54z93wQtBN7RHVYj8rNghBDCVBH+3xmxf0I=    172
OGKDrZQDB3yewZhoSd5qqvmG5A1GcNTYMexO95NlH+g=    148
WHsCtkOVsauvqBL0ULuG38887y7aU8GXdCmJMjw6hjQ=    145
SNlFRAsmUqnXKPofSXA8WYUc5DtmLcUMy4pXSJ3Ohz0=    131
vf6eQrnFfiS9o1kB/gRUJ4iTUixS9tHNKizqQ/1vLDI=    117
hQirtFbRr8t5T+/aVbrXM2tRNvoOIzChx5qzm1v/PE0=    104
IO+048XfFoL7X++ftIyb/zFKwNUUAkKaZLWrvg48TXA=     89
gzTushiuaWZwJShNepFWD+O9a7C76pAfW7Vc07jHXw8=     89
cmlCHjCLeo0TQK1S/37OqQK1AvwJWkD2h5HBd9lATgw=     78
dtype: int64

In [101]:
df_train = pd.read_csv('train_data.csv')
df_train.head()

                                           msno  is_churn
0  Pp9fOyd/eG4D7qs1jUnvFagO/9XcbAVNkufTX2Q7wkw=         0
1  nUiYMBsiB/HaDWMF20ebBeWtw3xwoWrIGuFWa/J/Adc=         0
2  U6POp25OGlgekxcGt8yayx+myCGmO/n71UPqYxxyxQs=         0
3  dN8D0n8vugg05OR4U8NHIkd5g7HIc9TTuR003ZdYWR0=         0
4  JZn5kjsN5nNtqfUtlpu/+XNYzSsqqiGzejuRLbbBtoE=         0

In [102]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 946686 entries, 0 to 946685
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   msno      946686 non-null  object
 1   is_churn  946686 non-null  int64
dtypes: int64(1), object(1)
memory usage: 14.4+ MB

In [106]:
df_train['is_churn'].value_counts(normalize=True) * 100

is_churn
0    91.005782
1     8.994218
Name: proportion, dtype: float64

In [107]:
df_train['msno'].nunique()

946686

In [108]:
df_train['msno'].duplicated().sum()

np.int64(0)

In [109]:
df_analysis = df_train.merge(
    df,
    on = 'msno',
    how='left'
)

In [110]:
df_analysis.head()

,msno,is_churn,city,bd,gender,registered_via,registration_init_time
0,Pp9fOyd/eG4D7qs1jUnvFagO/9XcbAVNkufTX2Q7wkw=,0,5.0,29.0,male,9.0,2011-09-11
1,nUiYMBsiB/HaDWMF20ebBeWtw3xwoWrIGuFWa/J/Adc=,0,13.0,36.0,male,9.0,2011-09-13
2,U6POp25OGlgekxcGt8yayx+myCGmO/n71UPqYxxyxQs=,0,13.0,40.0,male,9.0,2011-09-13
3,dN8D0n8vugg05OR4U8NHIkd5g7HIc9TTuR003ZdYWR0=,0,3.0,46.0,male,9.0,2011-09-16
4,JZn5kjsN5nNtqfUtlpu/+XNYzSsqqiGzejuRLbbBtoE=,0,4.0,28.0,female,9.0,2011-09-18

In [111]:
#все ли пользователи из df_train нашли данные в members

df_analysis.isna().sum()

msno                           0
is_churn                       0
city                      107153
bd                        569643
gender                    107153
registered_via            107153
registration_init_time    107153
dtype: int64

In [112]:
missing_members = df_analysis['city'].isna().sum()
missing_pct = missing_members / len(df_analysis) * 100

print(f'Нет данных в members: {missing_members:,} пользователей ({missing_pct:.1f}%)')

Нет данных в members: 107,153 пользователей (11.3%)

In [113]:
df_analysis['has_member_data'] = df_analysis['city'].notna().astype(int)

In [114]:
#среди пользователей без данных в members ушло примерно 5.3%;
#среди пользователей с данными в members ушло примерно 9.5%.

df_analysis.groupby('has_member_data')['is_churn'].mean() * 100

has_member_data
0    5.341894
1    9.460379
Name: is_churn, dtype: float64

In [115]:
#смотрим churn по признакам из members

df_analysis.groupby('gender')['is_churn'].mean() * 100

gender
female     12.998064
male       12.901188
unknown     6.587689
Name: is_churn, dtype: float64

In [116]:
df_analysis['gender'].value_counts(dropna=False)

gender
unknown    460298
male       199439
female     179796
NaN        107153
Name: count, dtype: int64

In [120]:
df_analysis.groupby('registered_via')['is_churn'].agg(['count', 'mean']).head()

                 count      mean
registered_via
3.0             103790  0.172001
4.0              51424  0.231098
7.0             451178  0.044758
9.0             229833  0.126892
13.0              3308  0.099456

In [119]:
df_analysis.groupby('city')['is_churn'].agg(['count', 'mean']).head()

       count      mean
city
1.0   431584  0.064057
3.0     4934  0.133360
4.0    46040  0.129235
5.0    69042  0.131789
6.0    25351  0.128831

In [121]:
bins = [0, 18, 25, 35, 45, 55, 65, 100]
labels = ['<18', '18-24', '25-34', '35-44', '45-54', '55-64', '65+']

df_analysis['age_group'] = pd.cut(
    df_analysis['bd'],
    bins=bins,
    labels=labels,
    right=False
)

In [122]:
df_analysis.groupby('age_group', observed=False)['is_churn'].agg(['count', 'mean'])

            count      mean
age_group
<18          9544  0.281119
18-24      102333  0.183812
25-34      172646  0.110782
35-44       64709  0.105395
45-54       21579  0.094073
55-64        5117  0.088724
65+          1104  0.113225

In [123]:
#проверим стаж пользователя

#сколько дней прошло с регистр
reference_date = pd.Timestamp('2017-04-30')
df_analysis['account_age_days'] = (
    reference_date - df_analysis['registration_init_time']
).dt.days

In [124]:
#переведем дни в годы
df_analysis['account_age_years'] = (
    df_analysis['account_age_days'] / 365.25
)

In [125]:
#сделаем группы по стажу
bins = [0, 1, 2, 3, 5, 10, 20]
labels = ['<1 year', '1-2', '2-3', '3-5', '5-10', '10+']

df_analysis['account_age_group'] = pd.cut(
    df_analysis['account_age_years'],
    bins=bins,
    labels=labels,
    right=False
)

In [126]:
account_churn = df_analysis.groupby(
    'account_age_group',
    observed=False
)['is_churn'].agg(['count', 'mean'])

account_churn['mean'] = account_churn['mean'] * 100

account_churn

                    count       mean
account_age_group
<1 year            151384   8.324526
1-2                196825   8.905373
2-3                 78831  12.275628
3-5                186924   9.969292
5-10               175463   9.700051
10+                 50106   7.905241

In [129]:
#кол-во транзакций на пользователя

transactions_agg = df_transactions.groupby('msno').agg(
    transactions_count = ('msno', 'size')
).reset_index()
transactions_agg.head()

                                           msno  transactions_count
0  +++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=                   1
1  +++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=                   1
2  +++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=                   2
3  +++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=                   1
4  ++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=                   1

In [133]:
#кто сделал больше всего транзакций
transactions_agg.sort_values(
    'transactions_count',
    ascending=False
).head(10)

                                                 msno  transactions_count
169646   72gJqt1O31E/WoxAEYFn9LHNI6mAZFGera5Q6gvsFkA=                 208
147797   5ty4nZkq54z93wQtBN7RHVYj8rNghBDCVBH+3xmxf0I=                 172
491279   OGKDrZQDB3yewZhoSd5qqvmG5A1GcNTYMexO95NlH+g=                 148
641623   WHsCtkOVsauvqBL0ULuG38887y7aU8GXdCmJMjw6hjQ=                 145
568572   SNlFRAsmUqnXKPofSXA8WYUc5DtmLcUMy4pXSJ3Ohz0=                 131
1116700  vf6eQrnFfiS9o1kB/gRUJ4iTUixS9tHNKizqQ/1vLDI=                 117
850292   hQirtFbRr8t5T+/aVbrXM2tRNvoOIzChx5qzm1v/PE0=                 104
381586   IO+048XfFoL7X++ftIyb/zFKwNUUAkKaZLWrvg48TXA=                  89
841675   gzTushiuaWZwJShNepFWD+O9a7C76pAfW7Vc07jHXw8=                  89
762797   cmlCHjCLeo0TQK1S/37OqQK1AvwJWkD2h5HBd9lATgw=                  78

In [159]:
#присоед transactions_agg к df_analysis

df_analysis = df_analysis.merge(
    transactions_agg,
    on='msno',
    how = 'left'
)

In [160]:
#36452 - пользователи, которые не делали транзакций
df_analysis['transactions_count'].isna().sum()

np.int64(36452)

In [161]:
df_analysis['transactions_count'] = (df_analysis['transactions_count'].fillna(0))

In [162]:
df_analysis.groupby('transactions_count')['is_churn'].agg(['count', 'mean']).head(10)

                     count      mean
transactions_count
0.0                  36452  0.786953
1.0                 797097  0.042749
2.0                  95979  0.144480
3.0                   8572  0.501983
4.0                   1752  0.613014
5.0                   1451  0.662302
6.0                    830  0.437349
7.0                    552  0.539855
8.0                    421  0.522565
9.0                    337  0.495549

In [163]:
last_transactions = (
    df_transactions.sort_values('transaction_date').groupby('msno').tail(1)
)

In [164]:
last_transactions = last_transactions[
    [
        'msno',
        'payment_plan_days',
        'plan_list_price',
        'actual_amount_paid',
        'is_auto_renew',
        'is_cancel',
        'transaction_date',
        'membership_expire_date'
    ]
]

In [165]:
df_analysis = df_analysis.merge(
    last_transactions,
    on='msno',
    how='left'
)

In [166]:
#Пользователи без активного автопродления имеют значительно более высокий churn отток
df_analysis.groupby('is_auto_renew')['is_churn'].agg(['count', 'mean'])

                count      mean
is_auto_renew
0.0             80795  0.306145
1.0            829439  0.038250

In [167]:
#is_cancel 1 - отменил автопродление
df_analysis.groupby('is_cancel')['is_churn'].agg(['count', 'mean'])

            count      mean
is_cancel
0.0        888482  0.043920
1.0         21752  0.801719

In [168]:
#Среди пользователей с включённым автопродлением какой процент отменяет подписку
pd.crosstab(
    df_analysis['is_auto_renew'],
    df_analysis['is_cancel'],
    normalize='index'
) * 100

is_cancel             0.0       1.0
is_auto_renew
0.0            100.000000  0.000000
1.0             97.377505  2.622495

In [169]:
#рассмотрим длительность подписки

df_analysis.groupby('payment_plan_days')['is_churn'].agg(['count', 'mean']).sort_values('count', ascending=False).head(15)

                    count      mean
payment_plan_days
30.0               892348  0.043893
410.0                4322  0.994216
90.0                 3614  0.931378
195.0                2860  0.994406
180.0                2859  0.994054
360.0                1201  0.985845
100.0                 623  0.995185
60.0                  481  0.698545
7.0                   422  0.874408
395.0                 283  1.000000
200.0                 261  0.992337
120.0                 182  0.961538
240.0                 179  0.949721
365.0                 152  0.993421
400.0                 145  1.000000

In [170]:
bins = [0, 31, 91, 181, 366, 1000]
labels = ['~1 month', '2-3 months', '4-6 months', '7-12 months', '12+ months']

df_analysis['plan_group'] = pd.cut(
    df_analysis['payment_plan_days'],
    bins=bins,
    labels=labels,
    right=False
)

In [171]:
plan_churn = df_analysis.groupby(
    'plan_group',
    observed=False
)['is_churn'].agg(['count', 'mean'])

plan_churn['mean'] = plan_churn['mean'] * 100
plan_churn

              count       mean
plan_group
~1 month     892947   4.442033
2-3 months     4121  90.439214
4-6 months     3671  99.264506
7-12 months    4660  99.034335
12+ months     4835  99.482937

In [172]:
df_analysis['has_discount'] = (
    df_analysis['actual_amount_paid'] < df_analysis['plan_list_price']
).astype(int)

In [173]:
#заплатил меньше прайса - 1, полную 0
discount_churn = df_analysis.groupby('has_discount')['is_churn'].agg(['count', 'mean'])
discount_churn['mean'] = discount_churn['mean'] * 100
discount_churn

               count       mean
has_discount
0             945028   8.938677
1               1658  40.651387

In [174]:
df_analysis['actual_amount_paid'].describe()

count    910234.000000
mean        144.824192
std         140.216801
min           0.000000
25%          99.000000
50%         149.000000
75%         149.000000
max        2000.000000
Name: actual_amount_paid, dtype: float64

In [176]:
df_analysis['payment_group'] = pd.cut(
    df_analysis['actual_amount_paid'],
    bins=[-1, 99, 149, 2000],
    labels=['0-99', '100-149', '150+']
)

In [177]:
df_analysis.groupby('payment_group', observed=False)['is_churn'].agg(['count', 'mean'])

                count      mean
payment_group
0-99           358181  0.028313
100-149        452765  0.051177
150+            99288  0.233150

In [178]:
#как связан размер платежа и длителььнось тарифа
pd.crosstab(
    df_analysis['payment_group'],
    df_analysis['plan_group'],
    normalize='index'
) * 100

plan_group      ~1 month  2-3 months  4-6 months  7-12 months  12+ months
payment_group
0-99           99.855380    0.077614    0.023452     0.039086    0.004467
100-149        99.992491    0.007509    0.000000     0.000000    0.000000
150+           83.144992    3.836315    3.612723     4.552413    4.853557

In [179]:
df_analysis.groupby('payment_group')['payment_plan_days'].mean()

C:\Users\User\AppData\Local\Temp\ipykernel_15024\3194195331.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_analysis.groupby('payment_group')['payment_plan_days'].mean()

payment_group
0-99       30.106195
100-149    30.003953
150+       65.302756
Name: payment_plan_days, dtype: float64

In [180]:
#Чем дольше пользователь ничего не делал, тем логичнее ожидать более высокий churn.

reference_date = pd.Timestamp('2017-04-30')

df_analysis['days_since_last_transaction'] = (
    reference_date - df_analysis['transaction_date']
).dt.days

In [181]:
df_analysis['days_since_last_transaction'].describe()

count    910234.000000
mean         44.446472
std          23.755719
min          30.000000
25%          35.000000
50%          43.000000
75%          52.000000
max         849.000000
Name: days_since_last_transaction, dtype: float64

In [182]:
bins = [-1, 7, 30, 60, 90, 180, 10000]
labels = [
    '0-7 days',
    '8-30 days',
    '31-60 days',
    '61-90 days',
    '91-180 days',
    '180+ days'
]

df_analysis['recency_group'] = pd.cut(
    df_analysis['days_since_last_transaction'],
    bins=bins,
    labels=labels
)

In [183]:
recency_churn = df_analysis.groupby(
    'recency_group',
    observed=False
)['is_churn'].agg(['count', 'mean'])

recency_churn['mean'] = recency_churn['mean'] * 100
recency_churn

                count       mean
recency_group
0-7 days            0        NaN
8-30 days      176520   1.752776
31-60 days     726616   6.445082
61-90 days       3315  85.852187
91-180 days      1400  95.142857
180+ days        2383  98.950902

In [184]:
df_analysis.to_csv('customer_retention_ready.csv', index=False)

In [185]:
df_analysis.dtypes

msno                                   object
is_churn                                int64
city                                  float64
bd                                    float64
gender                                 object
registered_via                        float64
registration_init_time         datetime64[ns]
transactions_count                    float64
payment_plan_days                     float64
plan_list_price                       float64
actual_amount_paid                    float64
is_auto_renew                         float64
is_cancel                             float64
transaction_date               datetime64[ns]
membership_expire_date         datetime64[ns]
plan_group                           category
has_discount                            int64
payment_group                        category
days_since_last_transaction           float64
recency_group                        category
dtype: object